export const memberDelegatedContactData = [
  {
    id: 1,
    SubscriberID: "87687676980",
    JivaMemberID: "98777",
    MemberFirstName: "Smith",
    MemberLastName: "John",
    Delegate: "PMS",
    Contact_Type: "Care Team - Delegated Care Coordinator",
    Contact_Name: 'Smith, John',
    Cell_Phone: '3957495934',
    Work_Phone: '9879847598',
    Email:'test@test.org',
    Preferred:"Cell Phone",
    Record_Active: "Y/N",
    Action:"",
    enableEditIcon: false
  },
  {
    id: 2,
    SubscriberID: "87687676992",
    JivaMemberID: "98779",
    MemberFirstName: "Tessa",
    MemberLastName: "Adam",
    Delegate: "Health Home - Carelink(Clovis)",
    Contact_Type: "CareLink Care Coordinator",
    Contact_Name: 'Tessa, Adam',
    Cell_Phone: '3645345453',
    Work_Phone: '4564564566',
    Email:'test@test.org',
    Preferred:"Work Phone",
    Record_Active: "Y/N",
    Action:"",
    enableEditIcon: false
  },
  {
    id: 3,
    SubscriberID: "87687676995",
    JivaMemberID: "98781",
    MemberFirstName: "Levi",
    MemberLastName: "Mark",
    Delegate: "PMG",
    Contact_Type: "-",
    Contact_Name: 'Levi, Mark',
    Cell_Phone: '-',
    Work_Phone: '-',
    Email:'-',
    Preferred:"-",
    Record_Active: "Y/N",
    Action:"",
    enableEditIcon: false
  },
  {
    id: 4,
    SubscriberID: "87687676997",
    JivaMemberID: "98782",
    MemberFirstName: "Chris",
    MemberLastName: "Alister",
    Delegate: "PMS",
    Contact_Type: "Unassigned",
    Contact_Name: 'Unassigned',
    Cell_Phone: '-',
    Work_Phone: '-',
    Email:'-',
    Preferred:"-",
    Record_Active: "Y/N",
    Action:"",
    enableEditIcon: false
  },
  {
    id: 5,
    SubscriberID: "87687676999",
    JivaMemberID: "98789",
    MemberFirstName: "Raj",
    MemberLastName: "Garg",
    Delegate: "PMG",
    Contact_Type: "-",
    Contact_Name: 'Raj, Garg',
    Cell_Phone: '-',
    Work_Phone: '-',
    Email:'-',
    Preferred:"-",
    Record_Active: "Y/N",
    Action:"",
    enableEditIcon: false
  },
  {
    id: 6,
    SubscriberID: "87687676899",
    JivaMemberID: "98791",
    MemberFirstName: "Ram",
    MemberLastName: "Kumar",
    Delegate: "PMG",
    Contact_Type: "-",
    Contact_Name: 'Ram, Kumar',
    Cell_Phone: '-',
    Work_Phone: '-',
    Email:'-',
    Preferred:"-",
    Record_Active: "Y/N",
    Action:"",
    enableEditIcon: false
  },
  {
    id: 7,
    SubscriberID: "87687676889",
    JivaMemberID: "98790",
    MemberFirstName: "karshit",
    MemberLastName: "jain",
    Delegate: "PMG",
    Contact_Type: "-",
    Contact_Name: 'karshit, jain',
    Cell_Phone: '-',
    Work_Phone: '-',
    Email:'-',
    Preferred:"-",
    Record_Active: "Y/N",
    Action:"",
    enableEditIcon: false
  },
  {
    id: 8,
    SubscriberID: "87687676879",
    JivaMemberID: "98788",
    MemberFirstName: "Atul",
    MemberLastName: "Dixit",
    Delegate: "PMG",
    Contact_Type: "-",
    Contact_Name: 'Atul, Dixit',
    Cell_Phone: '-',
    Work_Phone: '-',
    Email:'-',
    Preferred:"-",
    Record_Active: "Y/N",
    Action:"",
    enableEditIcon: false
  },
  {
    id: 9,
    SubscriberID: "87687676875",
    JivaMemberID: "98787",
    MemberFirstName: "Anurag",
    MemberLastName: "Gupta",
    Delegate: "PMG",
    Contact_Type: "-",
    Contact_Name: 'Anurag, Gupta',
    Cell_Phone: '-',
    Work_Phone: '-',
    Email:'-',
    Preferred:"-",
    Record_Active: "Y/N",
    Action:"",
    enableEditIcon: false
  },
  {
    id: 10,
    SubscriberID: "87687676874",
    JivaMemberID: "98783",
    MemberFirstName: "Ganesh",
    MemberLastName: "G",
    Delegate: "PMG",
    Contact_Type: "-",
    Contact_Name: 'Ganesh, G',
    Cell_Phone: '-',
    Work_Phone: '-',
    Email:'-',
    Preferred:"-",
    Record_Active: "Y/N",
    Action:"",
    enableEditIcon: false
  },

];
